# Generated by Django 4.2.2 on 2023-07-07 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(db_column='document_id', primary_key=True, serialize=False)),
                ('create_time', models.CharField(max_length=50)),
                ('update_time', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'document',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('log_id', models.AutoField(db_column='log_id', primary_key=True, serialize=False)),
                ('log_info', models.TextField()),
                ('update_time', models.CharField(max_length=50)),
                ('vertices_count', models.IntegerField()),
                ('edges_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('permission_id', models.AutoField(db_column='permission_id', primary_key=True, serialize=False)),
                ('permission_name', models.CharField(db_column='permission_name', max_length=50)),
            ],
            options={
                'db_table': 'permission',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(db_column='user_id', primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('role', models.IntegerField(choices=[(0, '普通用户'), (1, '管理员')])),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('user_permission_id', models.AutoField(db_column='user_permission_id', primary_key=True, serialize=False)),
                ('is_allowed', models.BooleanField(db_column='is_allowed', default=False)),
                ('permission', models.ForeignKey(db_column='permission_id', on_delete=django.db.models.deletion.CASCADE, to='app.permission')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'db_table': 'user_permission',
                'unique_together': {('user_id', 'permission_id')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='permission',
            field=models.ManyToManyField(through='app.UserPermission', to='app.permission'),
        ),
        migrations.CreateModel(
            name='QApair',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('document', models.ForeignKey(db_column='document_id', on_delete=django.db.models.deletion.CASCADE, to='app.document')),
            ],
            options={
                'db_table': 'q_a_document',
            },
        ),
    ]
