# Generated by Django 4.2.2 on 2024-03-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_log_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='qa_count',
            field=models.IntegerField(default=0),
        ),
    ]
